### PR TITLE
Add missing Info.plist.

### PR DESCRIPTION
**Pull request by sdefresne**
Building a framework requires an Info.plist, so add a template
that can be used to create the plist for the bundle.

### CODE REVIEW

**Comment by sdefresne** [comment]
@jverkoey Please triage.

**Comment by jverkoey** [comment]
Is there a corresponding framework project somewhere? Ideally this plist would live near that xcodeproj.

**Comment by sdefresne** [comment]
I don't know, but material-design-component does import the code using #import <MotionAnimator/MotionAnimator.h>. See for example https://github.com/material-components/material-components-ios/blob/7d1f3aed00675c25ab049e5ec3ec05e7762d014f/components/MaskedTransition/src/private/MDCMaskedPresentationController.m

**Comment by jverkoey** [comment]
I see. A couple questions:

- Who are you expecting to make use of this plist?
- Are you adding this file because you recently found that it was necessary somewhere?

**Comment by sdefresne** [comment]
I am adding it because MotionAnimator is a new dependency of material-components-ios that is used by Chromium on iOS (https://bugs.chromium.org/p/chromium/issues/detail?id=785248).

The build system used by Chromium on iOS do supports building libraries as framework bundle or as static libraries. However our build system requires that if framework style imports are used, then the code has to be build in a framework bundle.

Creating a framework bundle requires the presence of an Info.plist file (the application will be rejected if the Info.plist is missing or incorrect). Here the file I added is just the stock Info.plist that is added when creating a framework target in Xcode. It will be used by project that want to build the library as a framework bundle.

I have not integrated it to the build as 1. I don't really know MotionAnimator build system, 2. I think the decision of whether some code should be used as a framework bundle or a static library should be made by project integrating a library, not the implementor of the library (at least when possible).

**Review by jverkoey — APPROVED** [review]
Thanks for the context! I'll approve this PR, but can you move the plist file to a `resources/` sub-directory in the root of the repo please?

**Comment by sdefresne** [comment]
I've updated the PR to create the file at resources/Info.plist.

**Review by jverkoey — APPROVED** [review]

**Pull request merged**
